# @package _global_

defaults:
  - _self_
  - data: cryoem_maps # choose datamodule with `test_dataloader()` for evaluation
  - model: cryoten
  - network: cryoten_unetr
  - trainer: gpu
  - paths: default

  - hydra: default

  - optional local: default
  - evaluation: null


task_name: "eval_testset"

# This should be moved somewhere
prediction_writer:
  _target_: src.evaluation_utils.prediction_writer.PredictionsWriter
  output_dir: null
  write_interval: 'epoch'

trainer:
  # This is super important for some reason
  default_root_dir: null
  logger: null
  callbacks: null

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

# Hacked
input_map_path: null
output_map_path: null

map_save_prefix: ??? # file saved will be {map_save_prefix}_{emdb_id}.mrc
csv_path: ???
collection_dir: ${paths.data_dir}/collection
output_dir: ???